In [1]:
import numpy as np

In [6]:
# create 1D numpy array
arr1 = np.array([1, 2, 3])
print(type(arr1))
print(arr1.shape)  # get array dimensions

# create 2D numpy array
arr2 = np.array([[1, 2, 3], [2, 3, 4]])
print(arr2.shape)

arr3 = np.array([[1, 2, 3]])
print(arr3.shape)

<class 'numpy.ndarray'>
(3,)
(2, 3)
(1, 3)


In [7]:
print(f"arr1 has {arr1.ndim} dimensions")  # get number of array dimensions
print(f"arr2 has {arr2.ndim} dimensions")

arr1 has 1 dimensions
arr2 has 2 dimensions


In [9]:
# ndarray can only have one data type.
# Mixed data types will be casted to the larger data type.

arr1 = np.array([1, 2, 3])
print(f"{arr1} has data type {arr1.dtype}")

arr2 = np.array([1, 2, "test"])
print(f"{arr2} has data type {arr2.dtype}")

arr3 = np.array([1, 2, 3.0])
print(f"{arr3} has data type {arr3.dtype}")

[1 2 3] has data type int64
['1' '2' 'test'] has data type <U21
[1. 2. 3.] has data type float64


In [12]:
# Type conversions
array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [13]:
sequence_array = np.arange(10)  # similar to python range()
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [14]:
# zeros() and ones()

zero_array = np.zeros((3, 2), dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))  # defaults as float type
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [15]:
# reshape()

array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(2, 5)
print("array2:\n", array2)

array3 = array1.reshape(5, 2)
print("array3:\n", array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
# reshape() with dimension inference

array1 = np.arange(10)
array2 = array1.reshape(-1, 5)
print(f"array2 shape: {array2.shape}")
array3 = array1.reshape(5, -1)
print(f"array3 shape: {array3.shape}")

array2 shape: (2, 5)
array3 shape: (5, 2)


In [22]:
arr1 = np.arange(27)
arr1 = arr1.reshape(3, 3, 3)
arr1[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [23]:
# Boolean Indexing
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [24]:
# Sorting

org_array = np.array([3, 1, 9, 5])
print(f"Original array: {org_array}")
sort_array1 = np.sort(org_array)
print(f"Sorted array after np.sort(): {sort_array1}")

# Sort in descending order
sort_array1_desc = np.sort(org_array)[::-1]
print(f"Sort in descending order: {sort_array1_desc}")

Original array: [3 1 9 5]
Sorted array after np.sort(): [1 3 5 9]
Sort in descending order: [9 5 3 1]


In [25]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(f"Indices of sorted array: {sort_indices}")

Indices of sorted array: [1 0 3 2]


In [28]:
# dot() and transpose()

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print(f"dot product of A and B:\n{np.dot(A,B)}")

A = np.array([[1, 2], [3, 4]])
print(f"transpose of A:\n{np.transpose(A)}")

dot product of A and B:
[[ 58  64]
 [139 154]]
transpose of A:
[[1 3]
 [2 4]]
